### ISSUE TITLE
Breaking changes to jsonschema with examples

### ISSUE THREAD

**Issue by whitej6** [networktocode/schema-enforcer#155]
### Environment
* Python version:  3.8
* schema-enforcer version:  Latest

### Expected Behavior
Install schema-enforcer and be able to run examples

### Observed Behavior
Exception raise on unable to find `<path to site packages>/jsonschema/schemas/draft7.json`

### Steps to Reproduce
1. pip install schema-enforcer[ansible]
2. cd examples/ansible
3. schema-enforcer ansible

**Comment by PhillSimonds** [comment]
Thanks Jeremy!

Resolved per #157
