### ISSUE TITLE
Feature Request: Allow option to either install ansible-base or ansible as a package dependency

### ISSUE THREAD

**Issue by ryanmerolle** [networktocode/schema-enforcer#90]
### Environment
* Python version:  3.8.7
* schema-enforcer version:  1.0.1

### Proposed Functionality

Allow for option to use ansible or ansible-base.

### Use Case

I currently only leverage ansible-base with collections.  I rather not have ansible installed as a dependency for this package since I already use ansible-base.

**Comment by ryanmerolle** [comment]
ansible-lint allows for ansible-base to be installed by:
`pip install "ansible-lint[core]"`

**Comment by PhillSimonds** [comment]
@ryanmerolle thanks for the feedback! I believe you already talked with Ken. Just to close the loop -- we had some internal discussions about this and are looking at implementing the feature.
