### ISSUE TITLE
Implicit localhost not evaluate in schema-enforcer ansible

### ISSUE THREAD

**Issue by lvrfrc87** [networktocode/schema-enforcer#95]
### Environment
* Python version: Python 3.9.1
* schema-enforcer version: 1.0.1

### Expected Behavior
If ansible inventory is not passed to `schema-enforcer ansible` , schema enforcer should be able to include implicit `localhost` thus, variables under `group_vars/all` are not evaluated for example

### Observed Behavior

```
(root_venv) olivierif:cu-pretzels-networking-checks olivierif$ schema-enforcer ansible
[WARNING]: No inventory was parsed, only implicit localhost is available
Found 0 hosts in the inventory
ALL SCHEMA VALIDATION CHECKS PASSED
```

### Steps to Reproduce

Folder tree for reference

```
├── group_vars
│   └── all
│       ├── checks.yml
│       └── git.yml
├── schema
│   └── schemas
│       └── checks.yml
```

**Comment by PhillSimonds** [comment]
Thanks for opening this Federico! From a preliminary look at the code, I think it should be pretty easy to update the code so that it adds inventory vars to localhost and thus makes validation of vars associated assigned to the "all" group possible without defining an inventory. Is everyone OK with this approach?

**Comment by itdependsnetworks** [comment]
I am not currently seeing the benefit and may not be in line with the principal of least astonishment

**Comment by jmcgill298** [comment]
I would think the expected solution would be to add localhost to inventory

**Comment by lvrfrc87** [comment]
My point here is more about the user assuming that implicit localhost is passed based on the ansible WARNING as well as `Found 0 hosts in the inventory` (which assumes that an actual inventory has been passed to schema enforcer even if is not)

If we do not want to pass `localhost` is fine be me, even though I would suggest anyway to update the warning messages :)

**Comment by itdependsnetworks** [comment]
This is to be expected, as we simply carry over what Ansible does and have the same experience. The user can explicitly state the localhost, e.g. `-i localhost,` or chose to ignore the error.
